[package]
name = "vmod_fileserver"
version = "0.0.6"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
varnish = { git = "https://github.com/nyurik/varnish-rs.git", branch = "fixes-for-reqwest"}
varnish-sys = { git = "https://github.com/nyurik/varnish-rs.git", branch = "fixes-for-reqwest"}
varnish-macros = { git = "https://github.com/nyurik/varnish-rs.git", branch = "fixes-for-reqwest" }
chrono = "0.4.23"

[lib]
crate-type = ["cdylib"]
