[package]
name = "vmod_fileserver"
version = "0.0.6"
edition = "2021"
license = "BSD-3-Clause"

[build-dependencies]
varnish = "0.0.19"

[dependencies]
varnish = "0.0.19"
chrono = "0.4.23"

[lib]
crate-type = ["cdylib"]
