[package]
name = "vmod_fileserver"
version = "0.0.3"
edition = "2021"
license = "BSD-3-Clause"

[build-dependencies]
varnish = "0.0.15"

[dependencies]
varnish-sys = "0.0.15"
chrono = "0.4.23"

[lib]
crate-type = ["cdylib"]
