[package]
name = "vmod_fileserver"
version = "0.0.7"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
chrono = "0.4.23"
varnish = { version = "0.1.0", features = ["ffi"] }

[lib]
crate-type = ["cdylib"]
