[package]
name = "vmod_fileserver"
version = "0.0.6"
edition = "2021"
license = "BSD-3-Clause"

[build-dependencies]
#varnish = "0.0.19"
varnish = { path = "../varnish-rs/varnish" }

[dependencies]
varnish = { path = "../varnish-rs/varnish" }
varnish-sys = { path = "../varnish-rs/varnish-sys" }
chrono = "0.4.23"

[lib]
crate-type = ["cdylib"]
